import './globals.css';
import Navbar from './components/Navbar/Navbar';
import {
  AuthStatus,
  AuthContextProvider,
  RouteGuard,
} from './context/AuthContext';
import Footer from './components/Footer/Footer';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthContextProvider>
          <AuthStatus>
            <RouteGuard>
              <Navbar />
              {children}
              <Footer />
            </RouteGuard>
          </AuthStatus>
        </AuthContextProvider>
      </body>
    </html>
  );
}
