import './globals.css';
import Navbar from './components/Navbar';
import AuthParams, { AuthContextProvider } from './context/AuthContext';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  const { authIsReady } = AuthParams;

  console.log(authIsReady);
  return (
    <AuthContextProvider>
      <html lang="en">
        {authIsReady && (
          <body>
            <Navbar />
            {children}
          </body>
        )}
      </html>
    </AuthContextProvider>
  );
}
